name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Run spell check
      - name: Spell Check
        uses: reviewdog/action-misspell@v1
        with:
          locale: "en"
          reporter: "github-pr-review"
